# -*- coding: utf-8 -*-
"""Scraping Computing Reseaches of Bohol Island State University

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jyA1-oUpIQeUuWlsBz96TaKqEavTo_AB
"""

import csv
import html
import re
import time
from datetime import date
from typing import Dict, List, Optional, Tuple

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry


# =========================================================
# CONFIG
# =========================================================
CROSSREF_URL = "https://api.crossref.org/works"

MAILTO = "perinmaxangelo@gmail.com"

ROWS_PER_REQUEST = 500
START_YEAR = 2009
END_YEAR = date.today().year
OUTPUT_CSV = "bisu_computing_crossref_results.csv"

MAX_PAGES_PER_QUERY = 10
MAX_ITEMS_PER_QUERY = 5000

ALLOWED_TYPES = {
    "journal-article",
    "proceedings-article",
    "book-chapter",
    "book",
    "monograph",
    "report",
    "dissertation",
    "posted-content",
    "reference-entry",
}

# NOTE: removed "BISU" because it is too broad
AFFILIATION_QUERIES = [
    '"Bohol Island State University"',
    '"Bohol Island State University" Main Campus',
    '"Bohol Island State University" Balilihan',
    '"Bohol Island State University" Bilar',
    '"Bohol Island State University" Calape',
    '"Bohol Island State University" Candijay',
    '"Bohol Island State University" Clarin',
]

# =========================================================
# BISU CAMPUS ALIASES
# =========================================================
BISU_ALIAS_MAP: Dict[str, List[str]] = {
    "Main Campus": [
        "bohol island state university main campus",
        "bohol island state university tagbilaran",
        "bisu main campus",
        "bisu main",
    ],
    "Balilihan Campus": [
        "bohol island state university balilihan campus",
        "bohol island state university balilihan",
        "bisu balilihan campus",
        "bisu balilihan",
        "college of computing and information sciences bohol island state university balilihan campus",
    ],
    "Bilar Campus": [
        "bohol island state university bilar campus",
        "bohol island state university bilar",
        "bisu bilar campus",
        "bisu bilar",
        "computer science department college of technology bohol island state university bilar campus",
        "college of technology bohol island state university bilar campus",
    ],
    "Calape Campus": [
        "bohol island state university calape campus",
        "bohol island state university calape",
        "bisu calape campus",
        "bisu calape",
    ],
    "Candijay Campus": [
        "bohol island state university candijay campus",
        "bohol island state university candijay",
        "bisu candijay campus",
        "bisu candijay",
    ],
    "Clarin Campus": [
        "bohol island state university clarin campus",
        "bohol island state university clarin",
        "bisu clarin campus",
        "bisu clarin",
        "department of computer science bohol island state university clarin campus philippines",
        "college of science and management bohol island state university clarin philippines",
    ],
    "BISU (campus unspecified)": [
        "bohol island state university",
        "bohol island state university bohol philippines",
        "bohol island state university philippines",
        "bisu",
    ],
}

CAMPUS_TOKEN_RULES = {
    "Main Campus": [
        ["bohol", "island", "state", "university", "main"],
        ["bisu", "main"],
        ["bohol", "island", "state", "university", "tagbilaran"],
    ],
    "Balilihan Campus": [
        ["bohol", "island", "state", "university", "balilihan"],
        ["bisu", "balilihan"],
    ],
    "Bilar Campus": [
        ["bohol", "island", "state", "university", "bilar"],
        ["bisu", "bilar"],
    ],
    "Calape Campus": [
        ["bohol", "island", "state", "university", "calape"],
        ["bisu", "calape"],
    ],
    "Candijay Campus": [
        ["bohol", "island", "state", "university", "candijay"],
        ["bisu", "candijay"],
    ],
    "Clarin Campus": [
        ["bohol", "island", "state", "university", "clarin"],
        ["bisu", "clarin"],
    ],
}

# =========================================================
# COMPUTING FILTERS
# =========================================================
COMPUTING_KEYWORDS = [
    "computer science",
    "computer engineering",
    "information technology",
    "information system",
    "information systems",
    "informatics",
    "software engineering",
    "artificial intelligence",
    "machine learning",
    "deep learning",
    "neural network",
    "computer vision",
    "image processing",
    "natural language processing",
    "nlp",
    "data mining",
    "data science",
    "algorithm",
    "algorithms",
    "iot",
    "internet of things",
    "arduino",
    "robot",
    "robotics",
    "embedded system",
    "embedded systems",
    "rfid",
    "face recognition",
    "ocr",
    "classification",
    "prediction",
    "predictive",
    "web-based",
    "web based",
    "mobile application",
    "android application",
    "sensor",
    "monitoring system",
    "application programming interface",
    "api",
    "cloud",
    "network",
    "cybersecurity",
    "security",
    "automation",
    "simulation",
    "coppeliasim",
    "pcb",
    "optical inspection",
    "attendance system",
    "detection system",
    "recognition system",
]

COMPUTING_AFFILIATION_HINTS = [
    "department of computer science",
    "computer science department",
    "department of computer engineering",
    "computer engineering department",
    "department of information technology",
    "information technology department",
    "department of information systems",
    "information systems department",
    "college of computing and information sciences",
    "college of technology",
    "college of sciences",
    "college of science and management",
    "college of engineering",
    "faculty of engineering",
    "school of computing",
]

PROGRAM_RULES = {
    "Computer Science": [
        "computer science",
        "department of computer science",
        "computer science department",
    ],
    "Computer Engineering": [
        "computer engineering",
        "department of computer engineering",
        "computer engineering department",
        "embedded systems",
        "robotics",
        "arduino",
        "rfid",
        "pcb",
    ],
    "Information Technology": [
        "information technology",
        "department of information technology",
        "information technology department",
        "web-based",
        "mobile application",
        "android application",
    ],
    "Information Systems": [
        "information systems",
        "information system",
        "department of information systems",
        "information systems department",
    ],
}


# =========================================================
# HELPERS
# =========================================================
def build_session() -> requests.Session:
    session = requests.Session()

    retry = Retry(
        total=5,
        connect=5,
        read=5,
        backoff_factor=1.5,
        status_forcelist=[429, 500, 502, 503, 504],
        allowed_methods=["GET"],
        raise_on_status=False,
    )

    adapter = HTTPAdapter(max_retries=retry)
    session.mount("https://", adapter)
    session.mount("http://", adapter)

    session.headers.update({
        "User-Agent": f"{MAILTO} (BISU computing research Crossref harvester)",
        "Accept": "application/json",
    })

    return session


def normalize_text(text: Optional[str]) -> str:
    if not text:
        return ""
    text = html.unescape(text).lower()
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"[-_/(),.;:]", " ", text)
    text = re.sub(r"\bphl\b", "philippines", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def clean_text(text: Optional[str]) -> str:
    if not text:
        return ""
    text = html.unescape(text)
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def extract_year(item: dict) -> Optional[int]:
    date_fields = [
        item.get("published-print"),
        item.get("published-online"),
        item.get("issued"),
        item.get("created"),
    ]
    for field in date_fields:
        try:
            return int(field["date-parts"][0][0])
        except Exception:
            continue
    return None


def extract_title(item: dict) -> str:
    title = ""
    subtitle = ""

    if item.get("title"):
        title = " ".join([t for t in item["title"] if t]).strip()

    if item.get("subtitle"):
        subtitle = " ".join([s for s in item["subtitle"] if s]).strip()

    if title and subtitle:
        return f"{title}: {subtitle}"
    return title or subtitle or ""


def extract_venue(item: dict) -> str:
    event_name = ""
    if isinstance(item.get("event"), dict):
        event_name = item.get("event", {}).get("name", "") or ""

    container_title = ""
    if item.get("container-title"):
        container_title = " | ".join([c for c in item["container-title"] if c]).strip()

    publisher = (item.get("publisher") or "").strip()

    for candidate in [event_name, container_title, publisher]:
        if candidate:
            return candidate

    return "Unknown venue"


def extract_authors_and_affiliations(item: dict) -> Tuple[str, List[str]]:
    author_names = []
    affiliations = []

    for author in item.get("author", []):
        given = (author.get("given") or "").strip()
        family = (author.get("family") or "").strip()
        literal = (author.get("name") or "").strip()

        full_name = literal if literal else f"{given} {family}".strip()
        if full_name:
            author_names.append(full_name)

        for aff in author.get("affiliation", []) or []:
            aff_name = (aff.get("name") or "").strip()
            if aff_name:
                affiliations.append(aff_name)

    return ", ".join(author_names), affiliations


def match_bisu_campus(affiliations: List[str]) -> Tuple[Optional[str], Optional[str], str]:
    normalized_affiliations = [normalize_text(a) for a in affiliations if a]

    ordered_campuses = [
        "Main Campus",
        "Balilihan Campus",
        "Bilar Campus",
        "Calape Campus",
        "Candijay Campus",
        "Clarin Campus",
        "BISU (campus unspecified)",
    ]

    for campus in ordered_campuses:
        aliases = BISU_ALIAS_MAP.get(campus, [])
        for aff_raw, aff_norm in zip(affiliations, normalized_affiliations):
            for alias in aliases:
                if normalize_text(alias) in aff_norm:
                    return campus, aff_raw, "high"

    for campus, rule_groups in CAMPUS_TOKEN_RULES.items():
        for aff_raw, aff_norm in zip(affiliations, normalized_affiliations):
            for tokens in rule_groups:
                if all(token in aff_norm for token in tokens):
                    return campus, aff_raw, "medium"

    for aff_raw, aff_norm in zip(affiliations, normalized_affiliations):
        if "bohol island state university" in aff_norm or re.search(r"\bbisu\b", aff_norm):
            return "BISU (campus unspecified)", aff_raw, "low"

    return None, None, "none"


def infer_program(item: dict, affiliations: List[str]) -> str:
    title = extract_title(item)
    subjects = " ".join(item.get("subject", []) or [])
    container = " ".join(item.get("container-title", []) or [])
    publisher = item.get("publisher", "") or ""
    event_name = ""
    if isinstance(item.get("event"), dict):
        event_name = item.get("event", {}).get("name", "") or ""

    blob = normalize_text(
        f"{title} {subjects} {container} {publisher} {event_name} {' '.join(affiliations)}"
    )

    scores = {program: 0 for program in PROGRAM_RULES.keys()}

    for program, patterns in PROGRAM_RULES.items():
        for pattern in patterns:
            if pattern in blob:
                scores[program] += 1

    best_program = max(scores, key=scores.get)
    if scores[best_program] > 0:
        return best_program

    return "Computing (unspecified)"


def is_computing_record(item: dict, affiliations: List[str]) -> bool:
    title = extract_title(item)
    subjects = " ".join(item.get("subject", []) or [])
    container = " ".join(item.get("container-title", []) or [])
    publisher = item.get("publisher", "") or ""
    event_name = ""
    if isinstance(item.get("event"), dict):
        event_name = item.get("event", {}).get("name", "") or ""

    blob = normalize_text(
        f"{title} {subjects} {container} {publisher} {event_name} {' '.join(affiliations)}"
    )

    for kw in COMPUTING_KEYWORDS:
        if kw in blob:
            return True

    for hint in COMPUTING_AFFILIATION_HINTS:
        if hint in blob:
            return True

    return False


def dedup_key(row: dict) -> str:
    doi = (row.get("DOI") or "").strip().lower()
    if doi:
        return f"doi::{doi}"

    title = normalize_text(row.get("Title", ""))
    year = str(row.get("Year", ""))
    return f"title::{title}::year::{year}"


def get_total_results(
    session: requests.Session,
    affiliation_query: str,
    start_year: int,
    end_year: int,
) -> int:
    params = {
        "query.affiliation": affiliation_query,
        "filter": f"from-pub-date:{start_year}-01-01,until-pub-date:{end_year}-12-31",
        "rows": 0,
        "mailto": MAILTO,
    }

    response = session.get(CROSSREF_URL, params=params, timeout=60)

    if response.status_code != 200:
        print(f"[ERROR] count query='{affiliation_query}' status={response.status_code}")
        return -1

    payload = response.json()
    return payload.get("message", {}).get("total-results", -1)


# =========================================================
# FETCHER
# =========================================================
def fetch_crossref_for_affiliation(
    session: requests.Session,
    affiliation_query: str,
    start_year: int,
    end_year: int,
    rows_per_request: int = ROWS_PER_REQUEST,
) -> List[dict]:
    all_rows = []
    cursor = "*"
    page_num = 0

    seen_cursors = set()
    seen_page_signatures = set()

    while True:
        page_num += 1

        if page_num > MAX_PAGES_PER_QUERY:
            print(f"[STOP] query='{affiliation_query}' reached MAX_PAGES_PER_QUERY={MAX_PAGES_PER_QUERY}")
            break

        if cursor in seen_cursors:
            print(f"[STOP] query='{affiliation_query}' repeated cursor detected")
            break
        seen_cursors.add(cursor)

        params = {
            "query.affiliation": affiliation_query,
            "filter": f"from-pub-date:{start_year}-01-01,until-pub-date:{end_year}-12-31",
            "rows": rows_per_request,
            "cursor": cursor,
            "mailto": MAILTO,
        }

        response = session.get(CROSSREF_URL, params=params, timeout=60)

        if response.status_code != 200:
            print(f"[ERROR] query='{affiliation_query}' status={response.status_code}")
            print(response.text[:500])
            break

        payload = response.json()
        items = payload.get("message", {}).get("items", [])

        print(f"[INFO] Query='{affiliation_query}' page={page_num} fetched={len(items)}")

        if not items:
            print(f"[STOP] query='{affiliation_query}' no items returned")
            break

        # detect repeated page contents
        page_signature_parts = []
        for item in items[:10]:
            doi = (item.get("DOI") or "").strip().lower()
            title = extract_title(item).lower()
            year = extract_year(item)
            page_signature_parts.append(f"{doi}|{title}|{year}")

        page_signature = " || ".join(page_signature_parts)

        if page_signature in seen_page_signatures:
            print(f"[STOP] query='{affiliation_query}' repeated page signature detected")
            break
        seen_page_signatures.add(page_signature)

        kept_this_page = 0

        for item in items:
            work_type = item.get("type", "")
            if ALLOWED_TYPES and work_type not in ALLOWED_TYPES:
                continue

            year = extract_year(item)
            if year is None:
                continue

            title = extract_title(item)
            if not title:
                continue

            researchers, affiliations = extract_authors_and_affiliations(item)
            if not affiliations:
                continue

            campus, matched_aff, confidence = match_bisu_campus(affiliations)
            if not campus:
                continue

            if not is_computing_record(item, affiliations):
                continue

            program_inferred = infer_program(item, affiliations)
            venue = extract_venue(item)
            abstract = clean_text(item.get("abstract"))
            doi = item.get("DOI", "")
            url = item.get("URL", "")
            subjects = "; ".join(item.get("subject", []) or [])

            row = {
                "Year": year,
                "CampusMatched": campus,
                "CampusMatchedConfidence": confidence,
                "ProgramInferred": program_inferred,
                "Title": title,
                "Researchers": researchers,
                "Venue": venue,
                "Publisher": item.get("publisher", ""),
                "Type": work_type,
                "DOI": doi,
                "URL": url,
                "MatchedAffiliation": matched_aff or "",
                "AllAffiliations": " | ".join(affiliations),
                "Subjects": subjects,
                "Abstract": abstract,
                "CrossrefQueryUsed": affiliation_query,
            }

            all_rows.append(row)
            kept_this_page += 1

            if len(all_rows) >= MAX_ITEMS_PER_QUERY:
                print(f"[STOP] query='{affiliation_query}' reached MAX_ITEMS_PER_QUERY={MAX_ITEMS_PER_QUERY}")
                return all_rows

        print(f"[INFO] Query='{affiliation_query}' kept={kept_this_page} total_kept={len(all_rows)}")

        if len(items) < rows_per_request:
            print(f"[STOP] query='{affiliation_query}' last page reached")
            break

        next_cursor = payload.get("message", {}).get("next-cursor")
        if not next_cursor:
            print(f"[STOP] query='{affiliation_query}' no next cursor")
            break

        if next_cursor == cursor:
            print(f"[STOP] query='{affiliation_query}' next cursor same as current cursor")
            break

        cursor = next_cursor
        time.sleep(1.0)

    return all_rows


# =========================================================
# SAVE
# =========================================================
def save_to_csv(filename: str, rows: List[dict]) -> None:
    if not rows:
        print("[INFO] No rows found.")
        return

    fieldnames = [
        "Year",
        "CampusMatched",
        "CampusMatchedConfidence",
        "ProgramInferred",
        "Title",
        "Researchers",
        "Venue",
        "Publisher",
        "Type",
        "DOI",
        "URL",
        "MatchedAffiliation",
        "AllAffiliations",
        "Subjects",
        "Abstract",
        "CrossrefQueryUsed",
    ]

    with open(filename, "w", newline="", encoding="utf-8-sig") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

    print(f"[DONE] Saved {len(rows)} rows to '{filename}'")


# =========================================================
# MAIN
# =========================================================
def main():
    if MAILTO == "your-real-email@example.com":
        raise ValueError("Please replace MAILTO with your real email address first.")

    session = build_session()
    unique_keys = set()
    final_rows = []

    for aff_query in AFFILIATION_QUERIES:
        total = get_total_results(session, aff_query, START_YEAR, END_YEAR)
        print(f"\n[COUNT] {aff_query} -> total-results={total}")

        if total == -1:
            print(f"[SKIP] Could not get total results for '{aff_query}'")
            continue

        rows = fetch_crossref_for_affiliation(
            session=session,
            affiliation_query=aff_query,
            start_year=START_YEAR,
            end_year=END_YEAR,
            rows_per_request=ROWS_PER_REQUEST,
        )

        for row in rows:
            key = dedup_key(row)
            if key in unique_keys:
                continue
            unique_keys.add(key)
            final_rows.append(row)

    final_rows.sort(
        key=lambda r: (
            int(r["Year"]) if str(r["Year"]).isdigit() else 0,
            r["CampusMatched"],
            r["ProgramInferred"],
            r["Title"].lower(),
        ),
        reverse=True,
    )

    save_to_csv(OUTPUT_CSV, final_rows)

    print("\n[SUMMARY]")
    print(f"Unique BISU computing-related Crossref records found: {len(final_rows)}")

    campus_counts = {}
    program_counts = {}

    for row in final_rows:
        campus_counts[row["CampusMatched"]] = campus_counts.get(row["CampusMatched"], 0) + 1
        program_counts[row["ProgramInferred"]] = program_counts.get(row["ProgramInferred"], 0) + 1

    print("\nBy campus:")
    for campus, count in sorted(campus_counts.items(), key=lambda x: x[1], reverse=True):
        print(f"  - {campus}: {count}")

    print("\nBy inferred program:")
    for program, count in sorted(program_counts.items(), key=lambda x: x[1], reverse=True):
        print(f"  - {program}: {count}")


if __name__ == "__main__":
    main()